### PR TITLE
Allow LaravelAnalytics to be extended easier

### PR DESCRIPTION
**Pull request by BrandonSurowiec**
Added a binding for GoogleApiHelper to resolve the connection if the LaravelAnalytics class is extended.

### CODE REVIEW

**Comment by BrandonSurowiec** [comment]
This allows for easy adding of custom search functions in our own class. (Sample below)

**App\Analytics.php**

```
namespace App;

class Analytics extends \Spatie\LaravelAnalytics\LaravelAnalytics
{
    public function myCustomQuery() {
        // custom search queries
    }
}
```

**App\Analytics\AnalyticsFacade**
```
<?php

namespace App\Analytics;

use Illuminate\Support\Facades\Facade;

class AnalyticsFacade extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'App\Analytics';
    }
}
```

**config/app.php**
```
`'LaravelAnalytics' => App\Analytics\AnalyticsFacade::class,`
```

**Comment by BrandonSurowiec** [comment]
I just pushed a fix where I forgot to call `$this->getGoogleApiHelperClient();` to register the binding. I was doing it locally in my tests, but not on this patch.

**Comment by freekmurze** [comment]
Thanks for your contribution.Can you use of the `$app` that is passed down by the closures instead of using the `app()` helper function? Seems cleaner imho.

**Comment by BrandonSurowiec** [comment]
All fixed. Thanks for the feedback. :)

**Comment by freekmurze** [comment]
One more change: Move the contents of the `$this->getGoogleApiHelperClient();` to the top of the register method. Makes no sense have that as a seperate function anymore.

**Comment by BrandonSurowiec** [comment]
Done.

**Comment by BrandonSurowiec** [comment]
Will this change be able to be merged? I'd like to get rid of my dirty workarounds :)

**Comment by freekmurze** [comment]
Sorry, lost track of this one, will review it in the coming days.

**Comment by freekmurze** [comment]
You put `$this->guardAgainstMissingP12();` outside the bindings? Did you do that for a specific reason?

This will result in an exception being thrown when the package is installed and no `.p12` is present. 

In the old code this exception will only be thrown why trying to use the package.

**Comment by BrandonSurowiec** [comment]
Good catch. Unintentional. Would you like it in the bindings or in the `getGoogleClient()` method where it is used?

**Comment by freekmurze** [comment]
Inside `getGoogleClient()` looks like the right place.

**Comment by Wiejeben** [comment]
@freekmurze I take it this has not yet been implemented? What would be the recommended way of extending `\Spatie\LaravelAnalytics\LaravelAnalytics`?

**Comment by freekmurze** [comment]
Not yet, waiting on @BrandonSurowiec to do his magic (and fix the tests)

**Comment by freekmurze** [comment]
I'm currently working on a new major version of this package where this problem will be solved.

**Pull request closed without merging**
