### PR TITLE
Allow "Google_Service_Analytics_GaData" return type  for performQuery methods

### LINKED ISSUE #398: performQuery method signature requiring wrong return type
The performQuery() method returns an instance of Google_Service_Analytics_GaData. This is fine, but the method signature is requiring it to return `array | null`. So if strict types are enabled in PHP (it is by default), this blows up with:

```
Spatie\Analytics\AnalyticsClient::performQuery(): Return value must be of type ?array, Google_Service_Analytics_GaData returned
```

This can be reproduced by making any call to `Analytics::performQuery()` with strict types enabled.

### PR DESCRIPTION
**Pull request by oostation**
Fix #398

### CODE REVIEW

**Comment by WebMedic-X** [comment]
thank you!

**Comment by pdbreen** [comment]
Cant use v4.x without this fix.

**Comment by elfeffe** [comment]
This is needed, please merge

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
