### PR TITLE
Account Summaries List Function

### PR DESCRIPTION
**Pull request by robwilde**
I have made some small additions to allow for the Account Summaries list to be pulled in. Can then iterate through the list and provide the ability to allocate profile ID or multiple to a list of clients in a project.

My apologise if I have missed any protocols concerning submitting a pull request, this is the first time I have attempted to contribute to a project. Hope this helpful.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you very much for contributing. The code looks good. I'll try it out myself soon. If all is well I'll merge it and tag a new version.

**Comment by freekmurze** [comment]
In my tests the code doesn't return any workable output. Which fields are you expecting?

screen shot 2016-06-16 at 23 18 51

**Comment by robwilde** [comment]
My apologies, I didn't completely test the code as I should have and the returned results were inspected using dd(). I overlooked the private items returned.
I will refactor the code and supply the updated methods today for review.

**Comment by robwilde** [comment]
I went over and added two new methods to pair with the first one. Can now fetch the Accounts list, Properties list and the Properties profiles which contain the ANALYTICS_SITE_ID. I have also updated the readme file with more details to what they will return.

As with my project, I figured this would allow the creation of a selector and the ability to assign the ANALYTICS_SITE_ID to clients/users allocated in DB. 

I am sure it could be extended somewhat and perhaps simplified. The issue I found was the primary object returning private methods that need to be accessed with the correct function calls, and I wanted to keep my additions in LaravelAnalytics.php as clean and generic as possible.

Please forgive any adjustments I may have accidently made to the code style. I have auto code style configured in PHPstorm for PSR2. This is my first pull request so etiquette may be off. Thank you for allowing my to contribute and I hope this helps.

**Comment by freekmurze** [comment]
The full solution is quite a bit of code. If I accept this I would responsible for maintaining it for quite some time. Given that I don't need this functionality myself I've decided, even though your code is ok, not to merge the PR.

I'm currently working on a new major version of the package in which the main `Analytics` class much easier to extend than in the current version. So you can easily get your code to work in your own project.
ETA of the new version: somewhere this month or the beginning of July.

Please do not let this decision demotivate you from make future PR's to the spatie or other packages. I'm grateful for every PR, even the ones that don't get merged.

**Comment by robwilde** [comment]
No problem at all, I totally understand and look forward to the updated version. Thank you for the feedback

**Pull request closed without merging**
