### PR TITLE
 #265 Pagination Handling

### PR DESCRIPTION
**Pull request by amenk**

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you for your work on this.

I like the pagination handling functionality. Could you move that up to it's own helper class?

Please remove the logging stuff.

**Comment by amenk** [comment]
Thanks. I am not sure were to move it up to, in case it's a quick fix, I would be happy if you edit my PR :-)

**Comment by freekmurze** [comment]
Took a stab at this myself, and seems like there's too little to extract to a class, so I only cleaned it up a little bit.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
