### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by albirrkarim**
1. Update screenshot of newest google console layout
2. Add info for issue -> In newest version of google analytics, Google Analytics 4 (GA 4) not showing view id

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you for this. Could you PR the screenshots in a new "docs" directory in this package. I'll make sure to update the readme with links to the images in that directory.

**Comment by albirrkarim** [comment]
sure

**Comment by Oxicode** [comment]
ping @freekmurze

**Comment by freekmurze** [comment]
The current screenshots are a bit low res on a retina screen. Could you create retina screenshots (and maybe crop away the Google Chrome UI)?

**Comment by albirrkarim** [comment]
Im sorry i dont have retina display, i just can crop the google chrome UI, how about that ?

**Comment by Oxicode** [comment]
ohhh, yo tampoco tengo retina 😅
ohhh, I don't have a retina either 😅

**Pull request closed without merging**
